### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: meta-llama/Llama-2-7b-hf
adapter_name_or_path: saves/llama2-7b/lora/sft/bbh_ds0
template: fewshot
finetuning_type: lora

### export
export_dir: models/llama2_7b_lora_sft_bbh_ds0
export_size: 2
export_device: cpu
export_legacy_format: false