### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
adapter_name_or_path: saves/tinyllama/lora/sft/bbh_eval
template: fewshot
finetuning_type: lora

### export
export_dir: models/tinyllama_lora_sft_bbh_eval
export_size: 2
export_device: cpu
export_legacy_format: false